#!/usr/bin/env python3
"""Write ecb_rates.js: ECB USD-per-EUR reference rates bundled for the web app, so it
can convert to EUR without sending anything over the network.

Usage:
    python3 build_web_rates.py            # refresh from the ECB and rewrite ecb_rates.js
"""

import json
from datetime import date
from pathlib import Path

from fx import EcbRates

HERE = Path(__file__).resolve().parent
START = date(2010, 1, 1)


def main() -> None:
    fx = EcbRates(HERE / "fx" / "ecb_usd_per_eur.csv", START, date.today())
    days = [d for d in fx.days if d >= START]
    # Compact form: first date, then [days since previous rate, rate] pairs.
    pairs, prev = [], days[0]
    for d in days:
        pairs.append([(d - prev).days, fx.rates[d]])
        prev = d
    body = json.dumps({"start": days[0].isoformat(), "end": days[-1].isoformat(), "pairs": pairs},
                      separators=(",", ":"))
    out = HERE / "ecb_rates.js"
    out.write_text("// Generated by build_web_rates.py from ECB reference rates (USD per EUR). Do not edit.\n"
                   f"window.ECB_USD_RATES={body};\n", encoding="utf-8")
    print(f"Wrote {out}: {len(days)} rates, {days[0]} to {days[-1]}")


if __name__ == "__main__":
    main()
